version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TOKEN=${DATABASE_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true 